/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Pessoa;
import servicos.ServicosFactory;
import servicos.VitimasServicos;

/**
 *
 * @author 182310075
 */
public class JFVitima extends javax.swing.JFrame {

    /**
     * Creates new form JFVitima
     */
    public JFVitima() {
        initComponents();
        addRowToTable();
        jbEditarVitima.setVisible(false);
        jbDeletarVitima.setVisible(false);
    }
    
    public void addRowToTable() {
        //pega a modelagem da tabela na interface grafica
        DefaultTableModel model = (DefaultTableModel) jtVitimas.getModel();
        model.getDataVector().removeAllElements();//remove as linhas da tabela
        model.fireTableDataChanged();
        Object rowData[] = new Object[5];//cria vetor de 5 posicoes que corresponde as colunas da tabela
        VitimasServicos vitimaS = ServicosFactory.getVitimaServicos();//percorre lista e popula vetor e add vetor a tabela
        for (Pessoa vitima : vitimaS.listaVitimas()) {
            rowData[0] = vitima.getId();
            rowData[1] = vitima.getNome();
            rowData[2] = vitima.getOlho();
            rowData[3] = vitima.isSexo() == false ? "Feminino" : "Masculino"; //if Ternary Operator
            rowData[4] = vitima.getPontosDeVida();
            model.addRow(rowData);
        }
    }
    
    private void limpaCampos() {
        jtfNomeVitima.setText("");
        jtfCabeloVitima.setText("");
        jtfOlhoVitima.setText("");
        jtfPeleVitima.setText("");
        bgSexoVitima.clearSelection();
        jtfNomeVitima.requestFocus();
    }
    
    private boolean validaInputs() {
        if (jtfNomeVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preecher o nome");
            jtfNomeVitima.requestFocus();
            return false;
        }
        if (jtfCabeloVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preecher o cabelo");
            jtfCabeloVitima.requestFocus();
            return false;
        }
        if (jtfOlhoVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preecher o olho");
            jtfOlhoVitima.requestFocus();
            return false;
        }
        if (jtfPeleVitima.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preecher a pele");
            jtfPeleVitima.requestFocus();
            return false;
        }
        if (!jrbFemininoVitima.isSelected()
                && !jrbMasculinoVitima.isSelected()) {
            JOptionPane.showMessageDialog(this, "Selecionar Sexo");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexoVitima = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtfNomeVitima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfCabeloVitima = new javax.swing.JTextField();
        Olho = new javax.swing.JLabel();
        jtfOlhoVitima = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfPeleVitima = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbFemininoVitima = new javax.swing.JRadioButton();
        jrbMasculinoVitima = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jbSalvarVitima = new javax.swing.JButton();
        jbLimparVitima = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbDeletarVitima = new javax.swing.JButton();
        jbEditarVitima = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVitimas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Vitima");

        jLabel2.setText("Nome");

        jtfNomeVitima.setName("jtfNomeVitima"); // NOI18N

        jLabel3.setText("Cabelo");

        jtfCabeloVitima.setName("jtfCabeloVitima"); // NOI18N

        Olho.setText("Olho");

        jtfOlhoVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfOlhoVitimaActionPerformed(evt);
            }
        });

        jLabel4.setText("Pele");

        bgSexoVitima.add(jrbFemininoVitima);
        jrbFemininoVitima.setText("Feminino");

        bgSexoVitima.add(jrbMasculinoVitima);
        jrbMasculinoVitima.setText("Masculino");

        jLabel6.setText("Sexo");

        jbSalvarVitima.setText("Salvar");
        jbSalvarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarVitimaActionPerformed(evt);
            }
        });

        jbLimparVitima.setText("Limpar");
        jbLimparVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparVitimaActionPerformed(evt);
            }
        });

        jbDeletarVitima.setText("Deletar");
        jbDeletarVitima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarVitimaActionPerformed(evt);
            }
        });

        jbEditarVitima.setText("Editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfPeleVitima, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jtfCabeloVitima))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Olho)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbFemininoVitima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbMasculinoVitima)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfNomeVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbEditarVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletarVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbLimparVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvarVitima, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addComponent(jSeparator2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNomeVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCabeloVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Olho)
                    .addComponent(jtfOlhoVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfPeleVitima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jrbFemininoVitima)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMasculinoVitima)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarVitima)
                    .addComponent(jbLimparVitima)
                    .addComponent(jbDeletarVitima)
                    .addComponent(jbEditarVitima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtVitimas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Olho", "Sexo", "HP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVitimas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVitimasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVitimas);
        if (jtVitimas.getColumnModel().getColumnCount() > 0) {
            jtVitimas.getColumnModel().getColumn(0).setResizable(false);
            jtVitimas.getColumnModel().getColumn(1).setResizable(false);
            jtVitimas.getColumnModel().getColumn(2).setResizable(false);
            jtVitimas.getColumnModel().getColumn(3).setResizable(false);
            jtVitimas.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimparVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparVitimaActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_jbLimparVitimaActionPerformed

    private void jbSalvarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarVitimaActionPerformed
        // TODO add your handling code here:
        if (validaInputs()) {
            Pessoa v = new Pessoa();
            v.setNome(jtfNomeVitima.getText());
            v.setOlho(jtfOlhoVitima.getText());
            v.setCabelo(jtfCabeloVitima.getText());
            v.setPele(jtfPeleVitima.getText());
            if (jrbFemininoVitima.isSelected()
                    && jrbMasculinoVitima.isSelected()) {
                
                v.setSexo(!jrbFemininoVitima.isSelected());
    }//GEN-LAST:event_jbSalvarVitimaActionPerformed
            VitimasServicos vitimaS = ServicosFactory.getVitimaServicos();
            vitimaS.cadastrarVitima(v);
            addRowToTable();
            limpaCampos();
        }
    }
    private void jtfOlhoVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfOlhoVitimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfOlhoVitimaActionPerformed

    private void jtVitimasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVitimasMouseClicked
        // TODO add your handling code here:
        jbEditarVitima.setVisible(true);
        jbDeletarVitima.setVisible(true);
    }//GEN-LAST:event_jtVitimasMouseClicked

    private void jbDeletarVitimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarVitimaActionPerformed
        // TODO add your handling code here:
        int linha = jtVitimas.getSelectedRow();
        int id = (int) jtVitimas.getValueAt(linha, 0);
        String nome = (String) jtVitimas.getValueAt(linha, 1);
        Object[] btnMSG = {"Sim", "Não"};
        int resp = JOptionPane.showOptionDialog(this, "Deseja realmente deletar" + nome, ".:Deletar:.", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, btnMSG, btnMSG[0]);
        if (resp == 0) {
            VitimasServicos vitimaS = ServicosFactory.getVitimaServicos();
            vitimaS.deletarVitima(id);
            addRowToTable();
            JOptionPane.showMessageDialog(this, "Vitima" + nome + "deletada com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Ok, delete cancelado pelo usuário");
        }
        jbDeletarVitima.setVisible(false);
        jbEditarVitima.setVisible(false);
    }//GEN-LAST:event_jbDeletarVitimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVitima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVitima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Olho;
    private javax.swing.ButtonGroup bgSexoVitima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbDeletarVitima;
    private javax.swing.JButton jbEditarVitima;
    private javax.swing.JButton jbLimparVitima;
    private javax.swing.JButton jbSalvarVitima;
    private javax.swing.JRadioButton jrbFemininoVitima;
    private javax.swing.JRadioButton jrbMasculinoVitima;
    private javax.swing.JTable jtVitimas;
    private javax.swing.JTextField jtfCabeloVitima;
    private javax.swing.JTextField jtfNomeVitima;
    private javax.swing.JTextField jtfOlhoVitima;
    private javax.swing.JTextField jtfPeleVitima;
    // End of variables declaration//GEN-END:variables
}
